version: "3"

services:
  namenode:
    image: mfisser/hadoop-namenode:1.0.0-hadoop3.2.0-java8
    container_name: namenode
    networks:
      - shared
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"

  resourcemanager:
    image: mfisser/hadoop-resourcemanager:1.0.0-hadoop3.2.0-java8
    container_name: resourcemanager
    networks:
      - shared
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: mfisser/hadoop-historyserver:1.0.0-hadoop3.2.0-java8
    container_name: historyserver
    networks:
      - shared
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
  nodemanager1:
    image: mfisser/hadoop-nodemanager:1.0.0-hadoop3.2.0-java8
    container_name: nodemanager1
    networks:
      - shared
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
  
  datanode1:
    image: mfisser/hadoop-datanode:1.0.0-hadoop3.2.0-java8
    container_name: datanode1
    networks:
      - shared
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env  
    ports:
      - "50075:50075"

  datanode2:
    image: mfisser/hadoop-datanode:1.0.0-hadoop3.2.0-java8
    container_name: datanode2
    networks:
      - shared
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env     
    ports:
      - "50076:50076"

  datanode3:
    image: mfisser/hadoop-datanode:1.0.0-hadoop3.2.0-java8
    container_name: datanode3
    networks:
      - shared
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - "50077:50077"
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:

networks:
  shared