version: "3.2"

services:
  namenode:
    image: mfisser/hadoop-namenode:1.0.0-hadoop2.7.6-java8
    container_name: namenode
    volumes:
      - type: volume
        source: hadoop_namenode
        target: /hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: mfisser/hadoop-resourcemanager:1.0.0-hadoop2.7.6-java8
    container_name: resourcemanager
    volumes:
      - type: volume
        source: hadoop_resourcemanager
        target: /hadoop/resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: mfisser/hadoop-historyserver:1.0.0-hadoop2.7.6-java8
    container_name: historyserver
    volumes:
      - type: volume
        source: hadoop_historyserver
        target: /hadoop/yarn/timeline
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
  
  nodemanager1:
    image: mfisser/hadoop-nodemanager:1.0.0-hadoop2.7.6-java8
    container_name: nodemanager1
    volumes:
      - type: volume
        source: hadoop_nodemanager1
        target: /hadoop/nodemanager1    
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env

  nodemanager2:
    image: mfisser/hadoop-nodemanager:1.0.0-hadoop2.7.6-java8
    container_name: nodemanager2
    volumes:
      - type: volume
        source: hadoop_nodemanager2
        target: /hadoop/nodemanager2        
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env      
  
  datanode1:
    image: mfisser/hadoop-datanode:1.0.0-hadoop2.7.6-java8
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - type: volume
        source: hadoop_datanode1
        target: /hadoop/dfs/data
    env_file:
      - ./hadoop.env  

  datanode2:
    image: mfisser/hadoop-datanode:1.0.0-hadoop2.7.6-java8
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - type: volume
        source: hadoop_datanode2
        target: /hadoop/dfs/data
    env_file:
      - ./hadoop.env     

  datanode3:
    image: mfisser/hadoop-datanode:1.0.0-hadoop2.7.6-java8
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - type: volume
        source: hadoop_datanode3
        target: /hadoop/dfs/data
    env_file:
      - ./hadoop.env


volumes:
  hadoop_namenode:
    external: true
  hadoop_datanode1:
    external: true
  hadoop_datanode2:
    external: true
  hadoop_datanode3:
    external: true
  hadoop_historyserver:   
    external: true
  hadoop_resourcemanager:
    external: true
  hadoop_nodemanager1:
    external: true
  hadoop_nodemanager2:
    external: true
